import {useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,StyleSheet} from 'react-native';
export function WebQr({title,onRead,onClose}:{title:string;onRead:(s:string)=>void|Promise<void>;onClose:()=>void}) {
 const video=useRef<HTMLVideoElement>(null),controls=useRef<{stop():void}|null>(null),alive=useRef(true);
 const [text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{alive.current=false;controls.current?.stop();},[]);
 async function read(s:string){controls.current?.stop();try{await onRead(s);}catch{setError('No se pudo leer el código. Inténtalo de nuevo.');}}
 async function camera(){setError('');setBusy(true);try{const {BrowserQRCodeReader}=await import('@zxing/browser');const c=await new BrowserQRCodeReader().decodeFromConstraints({video:{facingMode:'environment'},audio:false},video.current!,r=>{if(r)void read(r.getText());});if(!alive.current)c.stop();else controls.current=c;}catch{if(alive.current)setError('No se pudo abrir la cámara. Puedes cargar una imagen del QR o pegar su contenido.');}finally{if(alive.current)setBusy(false);}}
 async function image(file?:File){if(!file)return;setError('');setBusy(true);const url=URL.createObjectURL(file);try{const {BrowserQRCodeReader}=await import('@zxing/browser');await read((await new BrowserQRCodeReader().decodeFromImageUrl(url)).getText());}catch{setError('No encontramos un QR en esa imagen. Prueba una captura más nítida.');}finally{URL.revokeObjectURL(url);if(alive.current)setBusy(false);}}
 return <View style={s.page}><View style={s.card}><Text style={s.title}>{title}</Text><Text style={s.copy}>Lee el QR de vinculación de Wybix. También puedes cargar una captura o pegar su contenido.</Text><video ref={video} playsInline muted autoPlay style={{width:'100%',maxHeight:260,borderRadius:16,background:'#09111e'}}/><Pressable accessibilityRole="button" disabled={busy} onPress={camera} style={s.button}><Text style={s.label}>{busy?'Abriendo…':'Abrir cámara'}</Text></Pressable><label style={{color:'#fff',fontSize:14}}>Imagen del QR<input aria-label="Imagen del QR" type="file" accept="image/*" onChange={e=>void image(e.target.files?.[0])} style={{display:'block',marginTop:8,width:'100%'}}/></label><TextInput accessibilityLabel="Contenido del QR" multiline value={text} onChangeText={setText} maxLength={12000} autoCapitalize="none" autoCorrect={false} placeholder="Pega aquí el contenido del QR" style={s.input}/><Pressable accessibilityRole="button" disabled={!text.trim()||busy} onPress={()=>void read(text.trim())} style={[s.button,!text.trim()&&{opacity:.5}]}><Text style={s.label}>Leer código</Text></Pressable>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<Pressable accessibilityRole="button" onPress={onClose} style={s.button}><Text style={s.label}>Cerrar</Text></Pressable></View></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0F1826',padding:20,overflow:'scroll'},card:{width:'100%',maxWidth:480,alignSelf:'center',gap:16,paddingBottom:30},title:{fontSize:22,fontWeight:'700',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#c6d5e7'},button:{backgroundColor:'#126b8a',padding:15,borderRadius:14,alignItems:'center'},label:{color:'#fff',fontWeight:'600'},input:{backgroundColor:'#fff',padding:14,minHeight:90,borderRadius:14,color:'#0F1826'},error:{color:'#ffbcaf',fontSize:14,lineHeight:20}});
